queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~=^\[*[Ww][Ii][Pp]
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
    merge_conditions:
      - base=main
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~=^\[*[Ww][Ii][Pp]
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
    update_method: rebase
    merge_method: merge

pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions: []
    actions:
      queue:
